### ISSUE TITLE
Problem to sign release apk since android studio 3.0

### ISSUE THREAD

**Issue by andreikeda** [foursquare/foursquare-android-oauth#12]
Hi, since I updated my android studio to 3.0.1 I've experienced a weird error when signing an apk.
Below are the messages:

Error:Error: commons-logging defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
Error:Error: httpclient defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
Error:Error: json defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
Error:Error: opengl-api defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
Error:Error: xmlParserAPIs defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
Error:Error: xpp3 defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]

I tried some solutions from internet such as declaring on submodule gradle
`exclude module: 'httpclient'
            exclude module: 'commons-logging'
            exclude group: 'org.json', module: 'json'
            exclude group: 'org.apache.httpcomponents'
            exclude module: 'opengl-api'
            exclude module: 'xmlParserAPIs'
            exclude module: 'xpp3'`

but no success =(
My gradle version is 3.0.1

![sem titulo-2 fw](https://user-images.githubusercontent.com/1785805/34075379-3b3d215c-e2ac-11e7-9126-cd4372564976.png)

**Comment by kuba91** [comment]
I also have werid problem using gradle-plugin in 3.0.1 version. While building project it was crashing at place where Build.VERSION_CODE was used and fix for my problem is importing foursquare-oath lib using:
implementation ('com.foursquare:foursquare-android-oauth:1.0.3'){
        exclude group: 'com.google.android'
    }

**Comment by erikcaffrey** [comment]
@andreikeda Did you found a solution? I also tried some solutions but I still have the same issue like you show it.

**Comment by andreikeda** [comment]
@erikcaffrey , i tried solution from @kuba91 and it worked.

**Comment by arkyminds-rajkumar** [comment]
hi , i also got same error , where i need to implement those line @kuba91 , @andreikeda ,kindly help me

**Comment by arkyminds-rajkumar** [comment]
ok thanks..
