### ISSUE TITLE
Configuration in Frameworks eg: Flutter with MapBox

### ISSUE THREAD

**Issue by ronaldG19** [foursquare/foursquare-android-oauth#13]
I wonder if there is any way or procedures to follow in configuring the api (Places API) in mobile frameworks such as Flutter,Xamarin etc.

**Comment by kylefowler** [comment]
hey @ronaldG19. What do mean by `configuring the API`?

**Comment by ronaldG19** [comment]
@kylefowler  to authorize it and link it to one of the Map Clients such as MapBox as it is compatible.
I picked Flutter Framework.
**I want to configure Places API in my Flutter project, I just signed up and have got my secret and client keys,How to proceed is my concern?**
