### ISSUE TITLE
Downgrade API level

### ISSUE THREAD

**Issue by dan-zx** [foursquare/foursquare-android-oauth#8]
Why are you using API level 17 when you are not using any of its features?

I'm building an app which API level is 10 and this error appears when I'm trying to compile it using foursquare-android-oauth version 1.0.2: 

```
Error:Execution failed for task ':prepareDebugDependencies'.
> ERROR: Debug has an indirect dependency on Android API level 15, but minSdkVersion for variant 'debug' is API level 10
```

I took the latest code from here and built a project with it targeting it to API level 7 and works fine. Why not use this API level instead?

**Comment by dannyroa** [comment]
Dan,

We just made changes so that you'll be able to set your own versions.

See https://github.com/foursquare/foursquare-android-oauth/blob/master/build.gradle.

Thanks.

**Comment by dan-zx** [comment]
Thanks :+1:
